// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: petFriend.proto

package com.etf.systemevents;

public final class PetFriend {
    private PetFriend() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface RequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        boolean hasTimeStampAkcije();
        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        com.google.protobuf.Timestamp getTimeStampAkcije();
        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        com.google.protobuf.TimestampOrBuilder getTimeStampAkcijeOrBuilder();

        /**
         * <code>string nazivMikroservisa = 2;</code>
         */
        String getNazivMikroservisa();
        /**
         * <code>string nazivMikroservisa = 2;</code>
         */
        com.google.protobuf.ByteString
        getNazivMikroservisaBytes();

        /**
         * <code>string Korisnik = 3;</code>
         */
        String getKorisnik();
        /**
         * <code>string Korisnik = 3;</code>
         */
        com.google.protobuf.ByteString
        getKorisnikBytes();

        /**
         * <code>.Request.tipAkcije Akcija = 4;</code>
         */
        int getAkcijaValue();
        /**
         * <code>.Request.tipAkcije Akcija = 4;</code>
         */
        com.etf.systemevents.PetFriend.Request.tipAkcije getAkcija();

        /**
         * <code>string nazivResursa = 5;</code>
         */
        String getNazivResursa();
        /**
         * <code>string nazivResursa = 5;</code>
         */
        com.google.protobuf.ByteString
        getNazivResursaBytes();
    }
    /**
     * Protobuf type {@code Request}
     */
    public  static final class Request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Request)
            RequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Request.newBuilder() to construct.
        private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Request() {
            nazivMikroservisa_ = "";
            korisnik_ = "";
            akcija_ = 0;
            nazivResursa_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.Timestamp.Builder subBuilder = null;
                            if (timeStampAkcije_ != null) {
                                subBuilder = timeStampAkcije_.toBuilder();
                            }
                            timeStampAkcije_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(timeStampAkcije_);
                                timeStampAkcije_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            nazivMikroservisa_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            korisnik_ = s;
                            break;
                        }
                        case 32: {
                            int rawValue = input.readEnum();

                            akcija_ = rawValue;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            nazivResursa_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_Request_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.etf.systemevents.PetFriend.Request.class, com.etf.systemevents.PetFriend.Request.Builder.class);
        }

        /**
         * Protobuf enum {@code Request.tipAkcije}
         */
        public enum tipAkcije
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>CREATE = 0;</code>
             */
            CREATE(0),
            /**
             * <code>DELETE = 1;</code>
             */
            DELETE(1),
            /**
             * <code>GET = 2;</code>
             */
            GET(2),
            /**
             * <code>UPDATE = 3;</code>
             */
            UPDATE(3),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>CREATE = 0;</code>
             */
            public static final int CREATE_VALUE = 0;
            /**
             * <code>DELETE = 1;</code>
             */
            public static final int DELETE_VALUE = 1;
            /**
             * <code>GET = 2;</code>
             */
            public static final int GET_VALUE = 2;
            /**
             * <code>UPDATE = 3;</code>
             */
            public static final int UPDATE_VALUE = 3;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static tipAkcije valueOf(int value) {
                return forNumber(value);
            }

            public static tipAkcije forNumber(int value) {
                switch (value) {
                    case 0: return CREATE;
                    case 1: return DELETE;
                    case 2: return GET;
                    case 3: return UPDATE;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<tipAkcije>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    tipAkcije> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<tipAkcije>() {
                        public tipAkcije findValueByNumber(int number) {
                            return tipAkcije.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.etf.systemevents.PetFriend.Request.getDescriptor().getEnumTypes().get(0);
            }

            private static final tipAkcije[] VALUES = values();

            public static tipAkcije valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private tipAkcije(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Request.tipAkcije)
        }

        public static final int TIMESTAMPAKCIJE_FIELD_NUMBER = 1;
        private com.google.protobuf.Timestamp timeStampAkcije_;
        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        public boolean hasTimeStampAkcije() {
            return timeStampAkcije_ != null;
        }
        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        public com.google.protobuf.Timestamp getTimeStampAkcije() {
            return timeStampAkcije_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStampAkcije_;
        }
        /**
         * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getTimeStampAkcijeOrBuilder() {
            return getTimeStampAkcije();
        }

        public static final int NAZIVMIKROSERVISA_FIELD_NUMBER = 2;
        private volatile Object nazivMikroservisa_;
        /**
         * <code>string nazivMikroservisa = 2;</code>
         */
        public String getNazivMikroservisa() {
            Object ref = nazivMikroservisa_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                nazivMikroservisa_ = s;
                return s;
            }
        }
        /**
         * <code>string nazivMikroservisa = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNazivMikroservisaBytes() {
            Object ref = nazivMikroservisa_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                nazivMikroservisa_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int KORISNIK_FIELD_NUMBER = 3;
        private volatile Object korisnik_;
        /**
         * <code>string Korisnik = 3;</code>
         */
        public String getKorisnik() {
            Object ref = korisnik_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                korisnik_ = s;
                return s;
            }
        }
        /**
         * <code>string Korisnik = 3;</code>
         */
        public com.google.protobuf.ByteString
        getKorisnikBytes() {
            Object ref = korisnik_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                korisnik_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AKCIJA_FIELD_NUMBER = 4;
        private int akcija_;
        /**
         * <code>.Request.tipAkcije Akcija = 4;</code>
         */
        public int getAkcijaValue() {
            return akcija_;
        }
        /**
         * <code>.Request.tipAkcije Akcija = 4;</code>
         * @return
         */
        public com.etf.systemevents.PetFriend.Request.tipAkcije getAkcija() {
            @SuppressWarnings("deprecation")
            com.etf.systemevents.PetFriend.Request.tipAkcije result = com.etf.systemevents.PetFriend.Request.tipAkcije.valueOf(akcija_);
            return result == null ? com.etf.systemevents.PetFriend.Request.tipAkcije.UNRECOGNIZED : result;
        }

        public static final int NAZIVRESURSA_FIELD_NUMBER = 5;
        private volatile Object nazivResursa_;
        /**
         * <code>string nazivResursa = 5;</code>
         */
        public String getNazivResursa() {
            Object ref = nazivResursa_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                nazivResursa_ = s;
                return s;
            }
        }
        /**
         * <code>string nazivResursa = 5;</code>
         */
        public com.google.protobuf.ByteString
        getNazivResursaBytes() {
            Object ref = nazivResursa_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                nazivResursa_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (timeStampAkcije_ != null) {
                output.writeMessage(1, getTimeStampAkcije());
            }
            if (!getNazivMikroservisaBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nazivMikroservisa_);
            }
            if (!getKorisnikBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, korisnik_);
            }
            if (akcija_ != com.etf.systemevents.PetFriend.Request.tipAkcije.CREATE.getNumber()) {
                output.writeEnum(4, akcija_);
            }
            if (!getNazivResursaBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nazivResursa_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (timeStampAkcije_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getTimeStampAkcije());
            }
            if (!getNazivMikroservisaBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nazivMikroservisa_);
            }
            if (!getKorisnikBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, korisnik_);
            }
            if (akcija_ != com.etf.systemevents.PetFriend.Request.tipAkcije.CREATE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(4, akcija_);
            }
            if (!getNazivResursaBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nazivResursa_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.etf.systemevents.PetFriend.Request)) {
                return super.equals(obj);
            }
            com.etf.systemevents.PetFriend.Request other = (com.etf.systemevents.PetFriend.Request) obj;

            boolean result = true;
            result = result && (hasTimeStampAkcije() == other.hasTimeStampAkcije());
            if (hasTimeStampAkcije()) {
                result = result && getTimeStampAkcije()
                        .equals(other.getTimeStampAkcije());
            }
            result = result && getNazivMikroservisa()
                    .equals(other.getNazivMikroservisa());
            result = result && getKorisnik()
                    .equals(other.getKorisnik());
            result = result && akcija_ == other.akcija_;
            result = result && getNazivResursa()
                    .equals(other.getNazivResursa());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasTimeStampAkcije()) {
                hash = (37 * hash) + TIMESTAMPAKCIJE_FIELD_NUMBER;
                hash = (53 * hash) + getTimeStampAkcije().hashCode();
            }
            hash = (37 * hash) + NAZIVMIKROSERVISA_FIELD_NUMBER;
            hash = (53 * hash) + getNazivMikroservisa().hashCode();
            hash = (37 * hash) + KORISNIK_FIELD_NUMBER;
            hash = (53 * hash) + getKorisnik().hashCode();
            hash = (37 * hash) + AKCIJA_FIELD_NUMBER;
            hash = (53 * hash) + akcija_;
            hash = (37 * hash) + NAZIVRESURSA_FIELD_NUMBER;
            hash = (53 * hash) + getNazivResursa().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.etf.systemevents.PetFriend.Request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.etf.systemevents.PetFriend.Request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Request)
                com.etf.systemevents.PetFriend.RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_Request_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_Request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.etf.systemevents.PetFriend.Request.class, com.etf.systemevents.PetFriend.Request.Builder.class);
            }

            // Construct using com.etf.system.PetFriend.Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                if (timeStampAkcijeBuilder_ == null) {
                    timeStampAkcije_ = null;
                } else {
                    timeStampAkcije_ = null;
                    timeStampAkcijeBuilder_ = null;
                }
                nazivMikroservisa_ = "";

                korisnik_ = "";

                akcija_ = 0;

                nazivResursa_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_Request_descriptor;
            }

            @Override
            public com.etf.systemevents.PetFriend.Request getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            @Override
            public com.etf.systemevents.PetFriend.Request build() {
                com.etf.systemevents.PetFriend.Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.etf.systemevents.PetFriend.Request buildPartial() {
                com.etf.systemevents.PetFriend.Request result = new com.etf.systemevents.PetFriend.Request(this);
                if (timeStampAkcijeBuilder_ == null) {
                    result.timeStampAkcije_ = timeStampAkcije_;
                } else {
                    result.timeStampAkcije_ = timeStampAkcijeBuilder_.build();
                }
                result.nazivMikroservisa_ = nazivMikroservisa_;
                result.korisnik_ = korisnik_;
                result.akcija_ = akcija_;
                result.nazivResursa_ = nazivResursa_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.etf.systemevents.PetFriend.Request) {
                    return mergeFrom((com.etf.systemevents.PetFriend.Request)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.etf.systemevents.PetFriend.Request other) {
                if (other == getDefaultInstance()) return this;
                if (other.hasTimeStampAkcije()) {
                    mergeTimeStampAkcije(other.getTimeStampAkcije());
                }
                if (!other.getNazivMikroservisa().isEmpty()) {
                    nazivMikroservisa_ = other.nazivMikroservisa_;
                    onChanged();
                }
                if (!other.getKorisnik().isEmpty()) {
                    korisnik_ = other.korisnik_;
                    onChanged();
                }
                if (other.akcija_ != 0) {
                    setAkcijaValue(other.getAkcijaValue());
                }
                if (!other.getNazivResursa().isEmpty()) {
                    nazivResursa_ = other.nazivResursa_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.etf.systemevents.PetFriend.Request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.etf.systemevents.PetFriend.Request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.Timestamp timeStampAkcije_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampAkcijeBuilder_;
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public boolean hasTimeStampAkcije() {
                return timeStampAkcijeBuilder_ != null || timeStampAkcije_ != null;
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public com.google.protobuf.Timestamp getTimeStampAkcije() {
                if (timeStampAkcijeBuilder_ == null) {
                    return timeStampAkcije_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStampAkcije_;
                } else {
                    return timeStampAkcijeBuilder_.getMessage();
                }
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public Builder setTimeStampAkcije(com.google.protobuf.Timestamp value) {
                if (timeStampAkcijeBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    timeStampAkcije_ = value;
                    onChanged();
                } else {
                    timeStampAkcijeBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public Builder setTimeStampAkcije(
                    com.google.protobuf.Timestamp.Builder builderForValue) {
                if (timeStampAkcijeBuilder_ == null) {
                    timeStampAkcije_ = builderForValue.build();
                    onChanged();
                } else {
                    timeStampAkcijeBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public Builder mergeTimeStampAkcije(com.google.protobuf.Timestamp value) {
                if (timeStampAkcijeBuilder_ == null) {
                    if (timeStampAkcije_ != null) {
                        timeStampAkcije_ =
                                com.google.protobuf.Timestamp.newBuilder(timeStampAkcije_).mergeFrom(value).buildPartial();
                    } else {
                        timeStampAkcije_ = value;
                    }
                    onChanged();
                } else {
                    timeStampAkcijeBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public Builder clearTimeStampAkcije() {
                if (timeStampAkcijeBuilder_ == null) {
                    timeStampAkcije_ = null;
                    onChanged();
                } else {
                    timeStampAkcije_ = null;
                    timeStampAkcijeBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public com.google.protobuf.Timestamp.Builder getTimeStampAkcijeBuilder() {

                onChanged();
                return getTimeStampAkcijeFieldBuilder().getBuilder();
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            public com.google.protobuf.TimestampOrBuilder getTimeStampAkcijeOrBuilder() {
                if (timeStampAkcijeBuilder_ != null) {
                    return timeStampAkcijeBuilder_.getMessageOrBuilder();
                } else {
                    return timeStampAkcije_ == null ?
                            com.google.protobuf.Timestamp.getDefaultInstance() : timeStampAkcije_;
                }
            }
            /**
             * <code>.google.protobuf.Timestamp timeStampAkcije = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
            getTimeStampAkcijeFieldBuilder() {
                if (timeStampAkcijeBuilder_ == null) {
                    timeStampAkcijeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                            getTimeStampAkcije(),
                            getParentForChildren(),
                            isClean());
                    timeStampAkcije_ = null;
                }
                return timeStampAkcijeBuilder_;
            }

            private Object nazivMikroservisa_ = "";
            /**
             * <code>string nazivMikroservisa = 2;</code>
             */
            public String getNazivMikroservisa() {
                Object ref = nazivMikroservisa_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    nazivMikroservisa_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string nazivMikroservisa = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNazivMikroservisaBytes() {
                Object ref = nazivMikroservisa_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    nazivMikroservisa_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string nazivMikroservisa = 2;</code>
             */
            public Builder setNazivMikroservisa(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                nazivMikroservisa_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string nazivMikroservisa = 2;</code>
             */
            public Builder clearNazivMikroservisa() {

                nazivMikroservisa_ = getDefaultInstance().getNazivMikroservisa();
                onChanged();
                return this;
            }
            /**
             * <code>string nazivMikroservisa = 2;</code>
             */
            public Builder setNazivMikroservisaBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                nazivMikroservisa_ = value;
                onChanged();
                return this;
            }

            private Object korisnik_ = "";
            /**
             * <code>string Korisnik = 3;</code>
             */
            public String getKorisnik() {
                Object ref = korisnik_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    korisnik_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string Korisnik = 3;</code>
             */
            public com.google.protobuf.ByteString
            getKorisnikBytes() {
                Object ref = korisnik_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    korisnik_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string Korisnik = 3;</code>
             */
            public Builder setKorisnik(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                korisnik_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string Korisnik = 3;</code>
             */
            public Builder clearKorisnik() {

                korisnik_ = getDefaultInstance().getKorisnik();
                onChanged();
                return this;
            }
            /**
             * <code>string Korisnik = 3;</code>
             */
            public Builder setKorisnikBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                korisnik_ = value;
                onChanged();
                return this;
            }

            private int akcija_ = 0;
            /**
             * <code>.Request.tipAkcije Akcija = 4;</code>
             */
            public int getAkcijaValue() {
                return akcija_;
            }
            /**
             * <code>.Request.tipAkcije Akcija = 4;</code>
             */
            public Builder setAkcijaValue(int value) {
                akcija_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>.Request.tipAkcije Akcija = 4;</code>
             */
            public com.etf.systemevents.PetFriend.Request.tipAkcije getAkcija() {
                @SuppressWarnings("deprecation")
                com.etf.systemevents.PetFriend.Request.tipAkcije result = com.etf.systemevents.PetFriend.Request.tipAkcije.valueOf(akcija_);
                return result == null ? com.etf.systemevents.PetFriend.Request.tipAkcije.UNRECOGNIZED : result;
            }
            /**
             * <code>.Request.tipAkcije Akcija = 4;</code>
             */
            public Builder setAkcija(com.etf.systemevents.PetFriend.Request.tipAkcije value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                akcija_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>.Request.tipAkcije Akcija = 4;</code>
             */
            public Builder clearAkcija() {

                akcija_ = 0;
                onChanged();
                return this;
            }

            private Object nazivResursa_ = "";
            /**
             * <code>string nazivResursa = 5;</code>
             */
            public String getNazivResursa() {
                Object ref = nazivResursa_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    nazivResursa_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string nazivResursa = 5;</code>
             */
            public com.google.protobuf.ByteString
            getNazivResursaBytes() {
                Object ref = nazivResursa_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    nazivResursa_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string nazivResursa = 5;</code>
             */
            public Builder setNazivResursa(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                nazivResursa_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string nazivResursa = 5;</code>
             */
            public Builder clearNazivResursa() {

                nazivResursa_ = getDefaultInstance().getNazivResursa();
                onChanged();
                return this;
            }
            /**
             * <code>string nazivResursa = 5;</code>
             */
            public Builder setNazivResursaBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                nazivResursa_ = value;
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Request)
        }

        // @@protoc_insertion_point(class_scope:Request)
        private static final com.etf.systemevents.PetFriend.Request DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.etf.systemevents.PetFriend.Request();
        }

        public static com.etf.systemevents.PetFriend.Request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Request>
                PARSER = new com.google.protobuf.AbstractParser<Request>() {
            @Override
            public Request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Request(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Request> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Request> getParserForType() {
            return PARSER;
        }

        @Override
        public com.etf.systemevents.PetFriend.Request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Response)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string porukaOdgovora = 1;</code>
         */
        String getPorukaOdgovora();
        /**
         * <code>string porukaOdgovora = 1;</code>
         */
        com.google.protobuf.ByteString
        getPorukaOdgovoraBytes();

        /**
         * <code>.Response.tipOdgovora Odgovor = 2;</code>
         */
        int getOdgovorValue();
        /**
         * <code>.Response.tipOdgovora Odgovor = 2;</code>
         */
        com.etf.systemevents.PetFriend.Response.tipOdgovora getOdgovor();
    }
    /**
     * Protobuf type {@code Response}
     */
    public  static final class Response extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Response)
            ResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Response.newBuilder() to construct.
        private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Response() {
            porukaOdgovora_ = "";
            odgovor_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Response(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            porukaOdgovora_ = s;
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            odgovor_ = rawValue;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_Response_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.etf.systemevents.PetFriend.Response.class, com.etf.systemevents.PetFriend.Response.Builder.class);
        }

        /**
         * Protobuf enum {@code Response.tipOdgovora}
         */
        public enum tipOdgovora
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>USPJESNO = 0;</code>
             */
            USPJESNO(0),
            /**
             * <code>GRESKA = 1;</code>
             */
            GRESKA(1),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>USPJESNO = 0;</code>
             */
            public static final int USPJESNO_VALUE = 0;
            /**
             * <code>GRESKA = 1;</code>
             */
            public static final int GRESKA_VALUE = 1;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static tipOdgovora valueOf(int value) {
                return forNumber(value);
            }

            public static tipOdgovora forNumber(int value) {
                switch (value) {
                    case 0: return USPJESNO;
                    case 1: return GRESKA;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<tipOdgovora>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    tipOdgovora> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<tipOdgovora>() {
                        public tipOdgovora findValueByNumber(int number) {
                            return tipOdgovora.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.etf.systemevents.PetFriend.Response.getDescriptor().getEnumTypes().get(0);
            }

            private static final tipOdgovora[] VALUES = values();

            public static tipOdgovora valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private tipOdgovora(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Response.tipOdgovora)
        }

        public static final int PORUKAODGOVORA_FIELD_NUMBER = 1;
        private volatile Object porukaOdgovora_;
        /**
         * <code>string porukaOdgovora = 1;</code>
         */
        public String getPorukaOdgovora() {
            Object ref = porukaOdgovora_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                porukaOdgovora_ = s;
                return s;
            }
        }
        /**
         * <code>string porukaOdgovora = 1;</code>
         */
        public com.google.protobuf.ByteString
        getPorukaOdgovoraBytes() {
            Object ref = porukaOdgovora_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                porukaOdgovora_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ODGOVOR_FIELD_NUMBER = 2;
        private int odgovor_;
        /**
         * <code>.Response.tipOdgovora Odgovor = 2;</code>
         */
        public int getOdgovorValue() {
            return odgovor_;
        }
        /**
         * <code>.Response.tipOdgovora Odgovor = 2;</code>
         */
        public com.etf.systemevents.PetFriend.Response.tipOdgovora getOdgovor() {
            @SuppressWarnings("deprecation")
            com.etf.systemevents.PetFriend.Response.tipOdgovora result = com.etf.systemevents.PetFriend.Response.tipOdgovora.valueOf(odgovor_);
            return result == null ? com.etf.systemevents.PetFriend.Response.tipOdgovora.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getPorukaOdgovoraBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, porukaOdgovora_);
            }
            if (odgovor_ != com.etf.systemevents.PetFriend.Response.tipOdgovora.USPJESNO.getNumber()) {
                output.writeEnum(2, odgovor_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getPorukaOdgovoraBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, porukaOdgovora_);
            }
            if (odgovor_ != com.etf.systemevents.PetFriend.Response.tipOdgovora.USPJESNO.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, odgovor_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.etf.systemevents.PetFriend.Response)) {
                return super.equals(obj);
            }
            com.etf.systemevents.PetFriend.Response other = (com.etf.systemevents.PetFriend.Response) obj;

            boolean result = true;
            result = result && getPorukaOdgovora()
                    .equals(other.getPorukaOdgovora());
            result = result && odgovor_ == other.odgovor_;
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + PORUKAODGOVORA_FIELD_NUMBER;
            hash = (53 * hash) + getPorukaOdgovora().hashCode();
            hash = (37 * hash) + ODGOVOR_FIELD_NUMBER;
            hash = (53 * hash) + odgovor_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.etf.systemevents.PetFriend.Response parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Response parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Response parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.etf.systemevents.PetFriend.Response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.etf.systemevents.PetFriend.Response prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Response)
                com.etf.systemevents.PetFriend.ResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_Response_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_Response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.etf.systemevents.PetFriend.Response.class, com.etf.systemevents.PetFriend.Response.Builder.class);
            }

            // Construct using com.etf.system.PetFriend.Response.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                porukaOdgovora_ = "";

                odgovor_ = 0;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_Response_descriptor;
            }

            @Override
            public com.etf.systemevents.PetFriend.Response getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            @Override
            public com.etf.systemevents.PetFriend.Response build() {
                com.etf.systemevents.PetFriend.Response result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.etf.systemevents.PetFriend.Response buildPartial() {
                com.etf.systemevents.PetFriend.Response result = new com.etf.systemevents.PetFriend.Response(this);
                result.porukaOdgovora_ = porukaOdgovora_;
                result.odgovor_ = odgovor_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.etf.systemevents.PetFriend.Response) {
                    return mergeFrom((com.etf.systemevents.PetFriend.Response)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.etf.systemevents.PetFriend.Response other) {
                if (other == getDefaultInstance()) return this;
                if (!other.getPorukaOdgovora().isEmpty()) {
                    porukaOdgovora_ = other.porukaOdgovora_;
                    onChanged();
                }
                if (other.odgovor_ != 0) {
                    setOdgovorValue(other.getOdgovorValue());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.etf.systemevents.PetFriend.Response parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.etf.systemevents.PetFriend.Response) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object porukaOdgovora_ = "";
            /**
             * <code>string porukaOdgovora = 1;</code>
             */
            public String getPorukaOdgovora() {
                Object ref = porukaOdgovora_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    porukaOdgovora_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string porukaOdgovora = 1;</code>
             */
            public com.google.protobuf.ByteString
            getPorukaOdgovoraBytes() {
                Object ref = porukaOdgovora_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    porukaOdgovora_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string porukaOdgovora = 1;</code>
             */
            public Builder setPorukaOdgovora(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                porukaOdgovora_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string porukaOdgovora = 1;</code>
             */
            public Builder clearPorukaOdgovora() {

                porukaOdgovora_ = getDefaultInstance().getPorukaOdgovora();
                onChanged();
                return this;
            }
            /**
             * <code>string porukaOdgovora = 1;</code>
             */
            public Builder setPorukaOdgovoraBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                porukaOdgovora_ = value;
                onChanged();
                return this;
            }

            private int odgovor_ = 0;
            /**
             * <code>.Response.tipOdgovora Odgovor = 2;</code>
             */
            public int getOdgovorValue() {
                return odgovor_;
            }
            /**
             * <code>.Response.tipOdgovora Odgovor = 2;</code>
             */
            public Builder setOdgovorValue(int value) {
                odgovor_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>.Response.tipOdgovora Odgovor = 2;</code>
             */
            public com.etf.systemevents.PetFriend.Response.tipOdgovora getOdgovor() {
                @SuppressWarnings("deprecation")
                com.etf.systemevents.PetFriend.Response.tipOdgovora result = com.etf.systemevents.PetFriend.Response.tipOdgovora.valueOf(odgovor_);
                return result == null ? com.etf.systemevents.PetFriend.Response.tipOdgovora.UNRECOGNIZED : result;
            }
            /**
             * <code>.Response.tipOdgovora Odgovor = 2;</code>
             */
            public Builder setOdgovor(com.etf.systemevents.PetFriend.Response.tipOdgovora value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                odgovor_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>.Response.tipOdgovora Odgovor = 2;</code>
             */
            public Builder clearOdgovor() {

                odgovor_ = 0;
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Response)
        }

        // @@protoc_insertion_point(class_scope:Response)
        private static final com.etf.systemevents.PetFriend.Response DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.etf.systemevents.PetFriend.Response();
        }

        public static com.etf.systemevents.PetFriend.Response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Response>
                PARSER = new com.google.protobuf.AbstractParser<Response>() {
            @Override
            public Response parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Response(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Response> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Response> getParserForType() {
            return PARSER;
        }

        @Override
        public com.etf.systemevents.PetFriend.Response getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Request_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Response_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Response_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\017petFriend.proto\032\037google/protobuf/times" +
                        "tamp.proto\"\337\001\n\007Request\0223\n\017timeStampAkcij" +
                        "e\030\001 \001(\0132\032.google.protobuf.Timestamp\022\031\n\021n" +
                        "azivMikroservisa\030\002 \001(\t\022\020\n\010Korisnik\030\003 \001(\t" +
                        "\022\"\n\006Akcija\030\004 \001(\0162\022.Request.tipAkcije\022\024\n\014" +
                        "nazivResursa\030\005 \001(\t\"8\n\ttipAkcije\022\n\n\006CREAT" +
                        "E\020\000\022\n\n\006DELETE\020\001\022\007\n\003GET\020\002\022\n\n\006UPDATE\020\003\"s\n\010" +
                        "Response\022\026\n\016porukaOdgovora\030\001 \001(\t\022&\n\007Odgo" +
                        "vor\030\002 \001(\0162\025.Response.tipOdgovora\"\'\n\013tipO" +
                        "dgovora\022\014\n\010USPJESNO\020\000\022\n\n\006GRESKA\020\00120\n\014Sys" +
                        "temEvents\022 \n\tlogAction\022\010.Request\032\t.Respo" +
                        "nseB\032\n\030com.etf.system\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        }, assigner);
        internal_static_Request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Request_descriptor,
                new String[] { "TimeStampAkcije", "NazivMikroservisa", "Korisnik", "Akcija", "NazivResursa", });
        internal_static_Response_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Response_descriptor,
                new String[] { "PorukaOdgovora", "Odgovor", });
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
